script_file <- gsub("~\\+~", " ", sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]))
phase_dir <- dirname(normalizePath(script_file))
setwd(dirname(phase_dir))
Sys.setenv(BIOINF_PHASE='6')
source(file.path(dirname(phase_dir), 'professional_pipeline.R'))
quit(save = 'no')
